config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :images
  resources :posts
  root to: "home#index"
  
  namespace 'api' do
    namespace 'v1' do
      post 'auth_user' => 'authentication#authenticate_user'
      post "sign_up" => 'registration#create'
      resources :images
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord

    mount_uploader :picture, PictureUploader
    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :images
  
end

app/controllers/api/v1/api_application_controller.rb
module Api
    module V1
        class ApiApplicationController < ActionController::Base
            
            attr_reader :current_user
            
            protected
            def authenticate_request!
                unless user_id_in_token?
                    render json: { errors: ['Not Authenticated'] }, status: :unauthorized
                    return
                end
                @current_user = User.find(auth_token[:user_id])
                rescue JWT::VerificationError, JWT::DecodeError
                render json: { errors: ['Not Authenticated'] }, status: :unauthorized
                end
            
            private
            def http_token
                @http_token ||= if request.headers['Authorization'].present?
                request.headers['Authorization'].split(' ').last
                end
            end
            def auth_token
                @auth_token ||= JsonWebToken.decode(http_token)
            end
            def user_id_in_token?
            http_token && auth_token && auth_token[:user_id].to_i
            end
       
       
        end
    end
end

app/controllers/api/v1/authentication_controller.rb
module Api
    module V1
        class AuthenticationController < ApiApplicationController
            
            def authenticate_user
                if User.find_for_database_authentication(email: params[:email]).present?
                user = User.find_for_database_authentication(email: params[:email])
                if user.valid_password?(params[:password])
                    render json: payload(user)
                else
                    render json: {errors: ['Password invalido' ]}, status: :unauthorized
                end
                else
                    render json: {errors: ['Isuario invalido']}, status: :unauthorized
                end
            end
        
            private
            def payload(user)
                return nil unless user and user.id 
                {
                   user: {id: user.id, email: user.email, name: user.name, auth_token: JsonWebToken.encode({user_id: user.id})}
                }
          end
          
        
        end
    end
end

app/controllers/api/v1/images_controller.rb
module Api
    module V1
        class ImagesController < ApiApplicationController
        
            before_action :authenticate_request!
            def index
                images = Image.order('created_at DESC');
                render json: {status: 'SUCCESS', message: 'Carga de imagenes', data: images},
                status: :ok
            end
            
            def show
                image = Image.find(params[:id])
                render json: {status: 'SUCCESS', message: 'Carga la imagen', data: image},
                status: :ok
            end

            def create 
                image = Image.new(image_params)
                if image.save 
                    render json: {status: 'SUCCESS', message: 'imagen guardada', data: image}, status: :ok
                else
                    render json: {status: 'ERROR', message: 'imagen no guardada', data: image}, status: :unprocessable_entity
                end
            end

            def destroy 
                image = Image.find(params[:id])
                image.destroy
                render json: {status: 'SUCCESS', message: 'imagen eliminada', data: image}, status: :ok
            end

            def update 
                image = Image.find(params[:id])
                if image.update_attributes(image_params)
                    render json: {status: 'SUCCESS', message: 'imagen editada', data: image}, status: :ok
                else
                    render json: {status: 'ERROR', message: 'imagen no editada', data: image}, status: :unprocessable_entity
                end
            end

            private

            def image_params
                params.permit(:description, :picture)
            end

        end
    end
end

app/controllers/api/v1/registration_controller.rb
module Api
    module V1
        class RegistrationController < ApiApplicationController
        
        respond_to :json
        def create
            user = User.new(user_params)
            if user.save
                render json: {status: 'SUCCESS', message: 'Usuario registrado',   user: {id: user.id, email: user.email, name: user.name, auth_token: JsonWebToken.encode({user_id: user.id})}, status: :ok}
            end

        end
        private
        def user_params
            params.permit(:name, :email, :password, :password_confirmation);
        end
        
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_devise_params, if: :devise_controller?

  def configure_devise_params

    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?

      @images = Image.order(id: :desc)
                    .where user_id: current_user.id
      
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    before_action :set_image, only: [:show, :edit, :update, :destroy]

    def index

      @images = Image.where user_id: current_user.id
        
    #ahora hacemos la consulta por medio del id del usuario
        
    end

    def new
        @image = Image.new
    end

    def edit
    end

    def create
        @image = current_user.images.new images_params
        @image.save
        redirect_to '/'
    end

    def show
    end

    def update
        @image.update images_params
        redirect_to @image
    end

    def destroy
        @image.destroy
        redirect_to images_path 
    end

    private

    def images_params
        params.require(:image).permit :description, :picture
    end 

    def set_image
        @image = Image.find params[:id]
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>

<% if user_signed_in? %>

    <h3> Bienvenido! <%= current_user.name %></h3>
    <div class="row">
        <%= render @images %>
    </div>

<%else%>

    <p> Por favor iniciar sesión para ver imagenes </p>

<% end %>

app/views/images/_form.html.erb
<div class="form-group">
    <%= form_for @image, :html => {:multipart => true} do |f| %>
        <%= f.label 'Descripción' %> <br>
        <%= f.text_field :description, class: 'form-control' %>
        <br>
        <%= f.label 'Cargar Imagen ' %> <br>
        <%= f.file_field :picture, class: 'form-control-file' %>
        <br>
        <%= f.submit 'Enviar', :class => 'btn btn-primary' %>
    <% end %>
</div>

app/views/images/_image.html.erb
<div class="col-sm-4">

<figure class="figure">

    <%= image_tag image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>

    <figcaption class="figure-caption">

        <%= image.description %>

        <%= link_to 'Editar', edit_image_path(image) %>

        <%= link_to 'Eliminar', image, method: :delete, data:{

        confirm: 'Esta seguro que decea eliminar esta imagen.'

        } %>

    </figcaption>

</figure>

</div>

app/views/images/edit.html.erb
<p>EDITAR IMAGENES</p>

<%= render 'form' %>

app/views/images/index.html.erb
<h1>hola Index</h1>
<div class="row">
    <%= render @images %>
</div>

app/views/images/new.html.erb
<p>EDITAR IMAGENES</p>

<%= render 'form' %>

app/views/images/show.html.erb
<%= @image.description %>
<%= image_tag @image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

     <ul class="nav justify-content-end ig-header-menu">

      <%- if user_signed_in? %>
        
        <li class="nav-item ig-item-menu">
          <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
        </li>
      
      <% else %>
        
        <li class="nav-item ig-item-menu">
          <%= link_to 'Iniciar Sesión', new_user_session_path %>
        </li>
   
        <li class="nav-item ig-item-menu">
          <%= link_to 'Registro', new_user_registration_path %>
    
        </li>
      
      <% end %>

    </ul>

    <div class='container'>
      <%= yield %>
    </div>

       <div class="ig-alert">

        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %> alert-dismissable" role="alert">
          <button type="button" data-dismiss="alert" class="close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= value %>
          </div>
          <% end %>
      </div>
   
  </body>
</html>